<a href="https://colab.research.google.com/github/0271679-debug/Estadistica-Inferencial/blob/main/Segundo_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================
# LISTAS, ÍNDICES, LIST COMPREHENSIONS,
# ARREGLOS Y MATRICES
# ============================================


# -------------------------
# 1. CREAR LISTAS
# -------------------------

L1 = [1, 2, 3, 4, 5]
L2 = [6, 7, 8, 9, 10]

# Listas pequeñas usadas después
L3 = [1]
L4 = [100]


# Mostrar L1
L1
# [1, 2, 3, 4, 5]


# -------------------------
# 2. ACCESO POR ÍNDICES
# -------------------------

L1[0]
# 1

L1[1]
# 2

L1[2]
# 3

L1[3]
# 4

L1[4]
# 5


# -------------------------
# 3. TUPLAS
# -------------------------

type((L1[4], L1[0]))
# tuple


# -------------------------
# 4. SUMAR LISTAS
# ELEMENTO POR ELEMENTO
# -------------------------

L = [
    L1[0] + L2[0],
    L1[1] + L2[1],
    L1[2] + L2[2],
    L1[3] + L2[3],
    L1[4] + L2[4]
]

L
# [7, 9, 11, 13, 15]


# -------------------------
# 5. RANGE
# -------------------------

type(range(0, 4))
# range


for i in range(0, 4):
    print(i)

# 0
# 1
# 2
# 3


for i in range(0, 5):
    print(i)

# 0
# 1
# 2
# 3
# 4


# -------------------------
# 6. LIST COMPREHENSION
# -------------------------

# Sumar L1 y L2 elemento por elemento

L = [L1[i] + L2[i] for i in range(0, 5)]

L
# [7, 9, 11, 13, 15]


# -------------------------
# 7. OPERACIONES CON
# LIST COMPREHENSION
# -------------------------

L2
# [6, 7, 8, 9, 10]


# Multiplicar cada elemento por 0.5

M = [0.5 * L2[i] for i in range(0, 5)]

M
# [3.0, 3.5, 4.0, 4.5, 5.0]


# Multiplicar cada elemento por 2

M = [2 * L2[i] for i in range(0, 5)]

M
# [12, 14, 16, 18, 20]


# ============================================
# ARREGLOS
# ============================================

# Un arreglo es una matriz en donde cada uno
# de sus elementos son números.
#
# Meta: convertir las listas ya creadas
# a vectores (arrays).


# -------------------------
# 8. IMPORTAR NUMPY
# -------------------------

import numpy as np


# -------------------------
# 9. CONVERTIR LISTAS
# EN ARRAYS
# -------------------------

L1_arreglo = np.array(L1)
L2_arreglo = np.array(L2)
L3_arreglo = np.array(L3)
L4_arreglo = np.array(L4)


# Verificar el tipo

type(L1_arreglo)
# numpy.ndarray


# -------------------------
# 10. OPERACIONES CON ARRAYS
# -------------------------

# Suma de vectores

L1_arreglo + L2_arreglo
# array([7, 9, 11, 13, 15])


# Multiplicación por escalar

2 * L1_arreglo
# array([2, 4, 6, 8, 10])


# Suma de arreglos pequeños

L3_arreglo + L4_arreglo
# array([101])


# IMPORTANTE:
# Para sumar dos arreglos elemento a elemento
# deben tener dimensiones compatibles.

# Por ejemplo:
# L2_arreglo + L4_arreglo
#
# Dependiendo de las dimensiones puede producir
# un ValueError por shapes incompatibles.


# ============================================
# MATRICES
# ============================================


# -------------------------
# 11. CREAR UNA LISTA
# -------------------------

List = [i for i in range(10, 30)]

List

# [10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
#  20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


# Número de elementos

len(List)
# 20


# -------------------------
# 12. CONVERTIR A ARRAY
# -------------------------

Array = np.array(List)

Array

# array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
#        20, 21, 22, 23, 24, 25, 26, 27, 28, 29])


# -------------------------
# 13. CREAR UNA MATRIZ
# -------------------------

Matriz1 = Array.reshape(5, 4)

Matriz1

# array([[10, 11, 12, 13],
#        [14, 15, 16, 17],
#        [18, 19, 20, 21],
#        [22, 23, 24, 25],
#        [26, 27, 28, 29]])

0
1
2
3
0
1
2
3
4


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])